/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransportRouteImport } from './routes/transport'
import { Route as MiceRouteImport } from './routes/mice'
import { Route as MarocRouteImport } from './routes/maroc'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VoyagesIndexRouteImport } from './routes/voyages.index'
import { Route as HajjOmraIndexRouteImport } from './routes/hajj-omra.index'
import { Route as VoyagesSlugRouteImport } from './routes/voyages.$slug'
import { Route as ReservationSlugRouteImport } from './routes/reservation.$slug'
import { Route as HajjOmraSlugRouteImport } from './routes/hajj-omra.$slug'

const TransportRoute = TransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => rootRouteImport,
} as any)
const MiceRoute = MiceRouteImport.update({
  id: '/mice',
  path: '/mice',
  getParentRoute: () => rootRouteImport,
} as any)
const MarocRoute = MarocRouteImport.update({
  id: '/maroc',
  path: '/maroc',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VoyagesIndexRoute = VoyagesIndexRouteImport.update({
  id: '/voyages/',
  path: '/voyages/',
  getParentRoute: () => rootRouteImport,
} as any)
const HajjOmraIndexRoute = HajjOmraIndexRouteImport.update({
  id: '/hajj-omra/',
  path: '/hajj-omra/',
  getParentRoute: () => rootRouteImport,
} as any)
const VoyagesSlugRoute = VoyagesSlugRouteImport.update({
  id: '/voyages/$slug',
  path: '/voyages/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationSlugRoute = ReservationSlugRouteImport.update({
  id: '/reservation/$slug',
  path: '/reservation/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HajjOmraSlugRoute = HajjOmraSlugRouteImport.update({
  id: '/hajj-omra/$slug',
  path: '/hajj-omra/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/maroc': typeof MarocRoute
  '/mice': typeof MiceRoute
  '/transport': typeof TransportRoute
  '/hajj-omra/$slug': typeof HajjOmraSlugRoute
  '/reservation/$slug': typeof ReservationSlugRoute
  '/voyages/$slug': typeof VoyagesSlugRoute
  '/hajj-omra/': typeof HajjOmraIndexRoute
  '/voyages/': typeof VoyagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/maroc': typeof MarocRoute
  '/mice': typeof MiceRoute
  '/transport': typeof TransportRoute
  '/hajj-omra/$slug': typeof HajjOmraSlugRoute
  '/reservation/$slug': typeof ReservationSlugRoute
  '/voyages/$slug': typeof VoyagesSlugRoute
  '/hajj-omra': typeof HajjOmraIndexRoute
  '/voyages': typeof VoyagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/maroc': typeof MarocRoute
  '/mice': typeof MiceRoute
  '/transport': typeof TransportRoute
  '/hajj-omra/$slug': typeof HajjOmraSlugRoute
  '/reservation/$slug': typeof ReservationSlugRoute
  '/voyages/$slug': typeof VoyagesSlugRoute
  '/hajj-omra/': typeof HajjOmraIndexRoute
  '/voyages/': typeof VoyagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/contact'
    | '/gallery'
    | '/maroc'
    | '/mice'
    | '/transport'
    | '/hajj-omra/$slug'
    | '/reservation/$slug'
    | '/voyages/$slug'
    | '/hajj-omra/'
    | '/voyages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/contact'
    | '/gallery'
    | '/maroc'
    | '/mice'
    | '/transport'
    | '/hajj-omra/$slug'
    | '/reservation/$slug'
    | '/voyages/$slug'
    | '/hajj-omra'
    | '/voyages'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/contact'
    | '/gallery'
    | '/maroc'
    | '/mice'
    | '/transport'
    | '/hajj-omra/$slug'
    | '/reservation/$slug'
    | '/voyages/$slug'
    | '/hajj-omra/'
    | '/voyages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  MarocRoute: typeof MarocRoute
  MiceRoute: typeof MiceRoute
  TransportRoute: typeof TransportRoute
  HajjOmraSlugRoute: typeof HajjOmraSlugRoute
  ReservationSlugRoute: typeof ReservationSlugRoute
  VoyagesSlugRoute: typeof VoyagesSlugRoute
  HajjOmraIndexRoute: typeof HajjOmraIndexRoute
  VoyagesIndexRoute: typeof VoyagesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transport': {
      id: '/transport'
      path: '/transport'
      fullPath: '/transport'
      preLoaderRoute: typeof TransportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mice': {
      id: '/mice'
      path: '/mice'
      fullPath: '/mice'
      preLoaderRoute: typeof MiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maroc': {
      id: '/maroc'
      path: '/maroc'
      fullPath: '/maroc'
      preLoaderRoute: typeof MarocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voyages/': {
      id: '/voyages/'
      path: '/voyages'
      fullPath: '/voyages/'
      preLoaderRoute: typeof VoyagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hajj-omra/': {
      id: '/hajj-omra/'
      path: '/hajj-omra'
      fullPath: '/hajj-omra/'
      preLoaderRoute: typeof HajjOmraIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voyages/$slug': {
      id: '/voyages/$slug'
      path: '/voyages/$slug'
      fullPath: '/voyages/$slug'
      preLoaderRoute: typeof VoyagesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservation/$slug': {
      id: '/reservation/$slug'
      path: '/reservation/$slug'
      fullPath: '/reservation/$slug'
      preLoaderRoute: typeof ReservationSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hajj-omra/$slug': {
      id: '/hajj-omra/$slug'
      path: '/hajj-omra/$slug'
      fullPath: '/hajj-omra/$slug'
      preLoaderRoute: typeof HajjOmraSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  MarocRoute: MarocRoute,
  MiceRoute: MiceRoute,
  TransportRoute: TransportRoute,
  HajjOmraSlugRoute: HajjOmraSlugRoute,
  ReservationSlugRoute: ReservationSlugRoute,
  VoyagesSlugRoute: VoyagesSlugRoute,
  HajjOmraIndexRoute: HajjOmraIndexRoute,
  VoyagesIndexRoute: VoyagesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
