/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangIndexRouteImport } from './routes/$lang.index'
import { Route as LangTransportRouteImport } from './routes/$lang.transport'
import { Route as LangMiceRouteImport } from './routes/$lang.mice'
import { Route as LangMarocRouteImport } from './routes/$lang.maroc'
import { Route as LangGalleryRouteImport } from './routes/$lang.gallery'
import { Route as LangContactRouteImport } from './routes/$lang.contact'
import { Route as LangAProposRouteImport } from './routes/$lang.a-propos'
import { Route as LangVoyagesIndexRouteImport } from './routes/$lang.voyages.index'
import { Route as LangHajjOmraIndexRouteImport } from './routes/$lang.hajj-omra.index'
import { Route as LangVoyagesSlugRouteImport } from './routes/$lang.voyages.$slug'
import { Route as LangReservationSlugRouteImport } from './routes/$lang.reservation.$slug'
import { Route as LangHajjOmraSlugRouteImport } from './routes/$lang.hajj-omra.$slug'

const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)
const LangTransportRoute = LangTransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => LangRoute,
} as any)
const LangMiceRoute = LangMiceRouteImport.update({
  id: '/mice',
  path: '/mice',
  getParentRoute: () => LangRoute,
} as any)
const LangMarocRoute = LangMarocRouteImport.update({
  id: '/maroc',
  path: '/maroc',
  getParentRoute: () => LangRoute,
} as any)
const LangGalleryRoute = LangGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => LangRoute,
} as any)
const LangContactRoute = LangContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LangRoute,
} as any)
const LangAProposRoute = LangAProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => LangRoute,
} as any)
const LangVoyagesIndexRoute = LangVoyagesIndexRouteImport.update({
  id: '/voyages/',
  path: '/voyages/',
  getParentRoute: () => LangRoute,
} as any)
const LangHajjOmraIndexRoute = LangHajjOmraIndexRouteImport.update({
  id: '/hajj-omra/',
  path: '/hajj-omra/',
  getParentRoute: () => LangRoute,
} as any)
const LangVoyagesSlugRoute = LangVoyagesSlugRouteImport.update({
  id: '/voyages/$slug',
  path: '/voyages/$slug',
  getParentRoute: () => LangRoute,
} as any)
const LangReservationSlugRoute = LangReservationSlugRouteImport.update({
  id: '/reservation/$slug',
  path: '/reservation/$slug',
  getParentRoute: () => LangRoute,
} as any)
const LangHajjOmraSlugRoute = LangHajjOmraSlugRouteImport.update({
  id: '/hajj-omra/$slug',
  path: '/hajj-omra/$slug',
  getParentRoute: () => LangRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/$lang/a-propos': typeof LangAProposRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/gallery': typeof LangGalleryRoute
  '/$lang/maroc': typeof LangMarocRoute
  '/$lang/mice': typeof LangMiceRoute
  '/$lang/transport': typeof LangTransportRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/hajj-omra/$slug': typeof LangHajjOmraSlugRoute
  '/$lang/reservation/$slug': typeof LangReservationSlugRoute
  '/$lang/voyages/$slug': typeof LangVoyagesSlugRoute
  '/$lang/hajj-omra/': typeof LangHajjOmraIndexRoute
  '/$lang/voyages/': typeof LangVoyagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang/a-propos': typeof LangAProposRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/gallery': typeof LangGalleryRoute
  '/$lang/maroc': typeof LangMarocRoute
  '/$lang/mice': typeof LangMiceRoute
  '/$lang/transport': typeof LangTransportRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/hajj-omra/$slug': typeof LangHajjOmraSlugRoute
  '/$lang/reservation/$slug': typeof LangReservationSlugRoute
  '/$lang/voyages/$slug': typeof LangVoyagesSlugRoute
  '/$lang/hajj-omra': typeof LangHajjOmraIndexRoute
  '/$lang/voyages': typeof LangVoyagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/$lang/a-propos': typeof LangAProposRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/gallery': typeof LangGalleryRoute
  '/$lang/maroc': typeof LangMarocRoute
  '/$lang/mice': typeof LangMiceRoute
  '/$lang/transport': typeof LangTransportRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/hajj-omra/$slug': typeof LangHajjOmraSlugRoute
  '/$lang/reservation/$slug': typeof LangReservationSlugRoute
  '/$lang/voyages/$slug': typeof LangVoyagesSlugRoute
  '/$lang/hajj-omra/': typeof LangHajjOmraIndexRoute
  '/$lang/voyages/': typeof LangVoyagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/$lang/a-propos'
    | '/$lang/contact'
    | '/$lang/gallery'
    | '/$lang/maroc'
    | '/$lang/mice'
    | '/$lang/transport'
    | '/$lang/'
    | '/$lang/hajj-omra/$slug'
    | '/$lang/reservation/$slug'
    | '/$lang/voyages/$slug'
    | '/$lang/hajj-omra/'
    | '/$lang/voyages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$lang/a-propos'
    | '/$lang/contact'
    | '/$lang/gallery'
    | '/$lang/maroc'
    | '/$lang/mice'
    | '/$lang/transport'
    | '/$lang'
    | '/$lang/hajj-omra/$slug'
    | '/$lang/reservation/$slug'
    | '/$lang/voyages/$slug'
    | '/$lang/hajj-omra'
    | '/$lang/voyages'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/$lang/a-propos'
    | '/$lang/contact'
    | '/$lang/gallery'
    | '/$lang/maroc'
    | '/$lang/mice'
    | '/$lang/transport'
    | '/$lang/'
    | '/$lang/hajj-omra/$slug'
    | '/$lang/reservation/$slug'
    | '/$lang/voyages/$slug'
    | '/$lang/hajj-omra/'
    | '/$lang/voyages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/transport': {
      id: '/$lang/transport'
      path: '/transport'
      fullPath: '/$lang/transport'
      preLoaderRoute: typeof LangTransportRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/mice': {
      id: '/$lang/mice'
      path: '/mice'
      fullPath: '/$lang/mice'
      preLoaderRoute: typeof LangMiceRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/maroc': {
      id: '/$lang/maroc'
      path: '/maroc'
      fullPath: '/$lang/maroc'
      preLoaderRoute: typeof LangMarocRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/gallery': {
      id: '/$lang/gallery'
      path: '/gallery'
      fullPath: '/$lang/gallery'
      preLoaderRoute: typeof LangGalleryRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/contact': {
      id: '/$lang/contact'
      path: '/contact'
      fullPath: '/$lang/contact'
      preLoaderRoute: typeof LangContactRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/a-propos': {
      id: '/$lang/a-propos'
      path: '/a-propos'
      fullPath: '/$lang/a-propos'
      preLoaderRoute: typeof LangAProposRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/voyages/': {
      id: '/$lang/voyages/'
      path: '/voyages'
      fullPath: '/$lang/voyages/'
      preLoaderRoute: typeof LangVoyagesIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/hajj-omra/': {
      id: '/$lang/hajj-omra/'
      path: '/hajj-omra'
      fullPath: '/$lang/hajj-omra/'
      preLoaderRoute: typeof LangHajjOmraIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/voyages/$slug': {
      id: '/$lang/voyages/$slug'
      path: '/voyages/$slug'
      fullPath: '/$lang/voyages/$slug'
      preLoaderRoute: typeof LangVoyagesSlugRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/reservation/$slug': {
      id: '/$lang/reservation/$slug'
      path: '/reservation/$slug'
      fullPath: '/$lang/reservation/$slug'
      preLoaderRoute: typeof LangReservationSlugRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/hajj-omra/$slug': {
      id: '/$lang/hajj-omra/$slug'
      path: '/hajj-omra/$slug'
      fullPath: '/$lang/hajj-omra/$slug'
      preLoaderRoute: typeof LangHajjOmraSlugRouteImport
      parentRoute: typeof LangRoute
    }
  }
}

interface LangRouteChildren {
  LangAProposRoute: typeof LangAProposRoute
  LangContactRoute: typeof LangContactRoute
  LangGalleryRoute: typeof LangGalleryRoute
  LangMarocRoute: typeof LangMarocRoute
  LangMiceRoute: typeof LangMiceRoute
  LangTransportRoute: typeof LangTransportRoute
  LangIndexRoute: typeof LangIndexRoute
  LangHajjOmraSlugRoute: typeof LangHajjOmraSlugRoute
  LangReservationSlugRoute: typeof LangReservationSlugRoute
  LangVoyagesSlugRoute: typeof LangVoyagesSlugRoute
  LangHajjOmraIndexRoute: typeof LangHajjOmraIndexRoute
  LangVoyagesIndexRoute: typeof LangVoyagesIndexRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangAProposRoute: LangAProposRoute,
  LangContactRoute: LangContactRoute,
  LangGalleryRoute: LangGalleryRoute,
  LangMarocRoute: LangMarocRoute,
  LangMiceRoute: LangMiceRoute,
  LangTransportRoute: LangTransportRoute,
  LangIndexRoute: LangIndexRoute,
  LangHajjOmraSlugRoute: LangHajjOmraSlugRoute,
  LangReservationSlugRoute: LangReservationSlugRoute,
  LangVoyagesSlugRoute: LangVoyagesSlugRoute,
  LangHajjOmraIndexRoute: LangHajjOmraIndexRoute,
  LangVoyagesIndexRoute: LangVoyagesIndexRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
